### ISSUE TITLE
Windows stop resizing when too narrow

### ISSUE THREAD

**Issue by mil** [mackstann/tinywm#1]
Not sure if this is within the scope of TinyWM, but I modified TinyWM so that the windows when resizing with Mod+Secondary Click will flip over. Thus when resizing you don't "hit the border" when dragging right/up but rather the window is just flipped / continues to resize.

See my commit here:
https://github.com/mil/tinywm/commit/b71169f88350d6b6fa6c9cf7c00b8bf1c4afe3d4

Let me know if you want me to issue a pull request. By the way - thanks for TinyWM - huge fan!

**Comment by mackstann** [comment]
Hi, thanks for sending this my way. I do think it is out of scope, though.
It's an extra feature that even most typical WM's don't have. But if you
want to maintain this and other changes in a fork, you have my
encouragement!

On Fri, Jun 8, 2012 at 1:07 PM, Miles Sandlar <
reply@reply.github.com
